title: dpt106
description: Personal blog and website
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

minima:
  skin: auto
  social_links:
    github: dpt106
